
CREATE TABLE USER (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED DATE,
    MODIFIED DATE,
    LAST_LOGIN DATE,
    TOKEN VARCHAR(255)
);

CREATE TABLE PHONE (
    ID INTEGER NOT NULL PRIMARY KEY,
    DDD VARCHAR(255),
    NUMBER VARCHAR(255)
);